apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-api-ingress
  namespace: infinion
  labels:
    app: weather-api
  annotations:
    # NGINX ingress controller
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # Redirect HTTP to HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx

  # TLS configuration with automatic certificate from Let's Encrypt
  tls:
    - hosts:
        - infinion-weather.sherifdeenadebayo.com
      secretName: weather-api-tls-cert

  # Route rules
  rules:
    - host: infinion-weather.sherifdeenadebayo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weather-api-svc
                port:
                  number: 80
